drop table training if exists;
create table training (
  id integer primary key GENERATED BY DEFAULT AS IDENTITY(START WITH 1),
  user_id integer,
  schedule_date date,
  description varchar(4000),
  training_type varchar(200)

);

drop table user if exists;
create table user (
  id integer primary key GENERATED BY DEFAULT AS IDENTITY(START WITH 100),
  username varchar(50) not null,
  email varchar(50) not null,
  pw varchar(255) not null
);



ALTER TABLE training ADD FOREIGN KEY (user_id) REFERENCES user(id);